# Generated by Django 5.0.6 on 2024-05-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_studentsubmission_student_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
